/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        faluRed: '#6f1d1b',
        peach: '#efbc9b',
        cambridgeBlue: '#70a288',
        blackOlive: '#37423d',
        outerSpace: '#435058',
        brown: '#522b1f',
        maroon: '#512c34',
        lightMaroon: '#6a373b',
        rose: '#93737e',
        darkBrown: '#2e1209',
        midnightGreen: '#073B4C',
        columbiaBlue: '#B9D6F2',
        viridianGreen: '#B9D6F2',
        chocolateCosmos: '#4C061D',
        melon: '#F9ADA0',
        purplePink: '#9A7AA0',
        chinaRose: '#B56576',
        vanilla: '#E4D6A7',
        mimiPink: '#F5D7E3',
        cherryBlossom: '#F4A5AE',
        teaRose: '#DEBAC0',
        snow: '#F4EDED',
        walnutBrown: '#5E503F',
        beaverBrown: '#A9927D',
        lavender: '##D8D2E1',
        paleDogwood: '#FFDDD2',
        honeydewGreen: '#F0F8EA',
        nyanza: '#DAF7DC',
      },
      backgroundImage: {
        coffee: "url('../assets/images/coffeeAbout.jpeg')",
        interior: "url('../assets/images/interiorAbout.jpeg')",
      },
    },
  },
  plugins: [],
}
